# Generated by Django 3.0.3 on 2020-07-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('memo', models.TextField(blank=True, verbose_name='备注')),
                ('cmd', models.TextField(verbose_name='命令')),
                ('num', models.IntegerField(blank=True, default=0, verbose_name='次数')),
            ],
            options={
                'verbose_name': '历史命令',
                'verbose_name_plural': '历史命令',
            },
        ),
    ]
