# Generated by Django 3.0.3 on 2020-07-27 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdbs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='num',
            field=models.IntegerField(blank=True, default=1, verbose_name='次数'),
        ),
    ]
