# Generated by Django 3.0.3 on 2020-07-27 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdbs', '0002_auto_20200727_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('memo', models.TextField(blank=True, verbose_name='备注')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='主机组')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='代码')),
            ],
            options={
                'verbose_name': '主机组',
                'verbose_name_plural': '主机组',
            },
        ),
        migrations.CreateModel(
            name='Idc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('memo', models.TextField(blank=True, verbose_name='备注')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='名称')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='代码')),
                ('country', models.CharField(blank=True, max_length=32, null=True, verbose_name='地址')),
                ('area', models.CharField(blank=True, max_length=32, null=True, verbose_name='地址')),
                ('addr', models.CharField(blank=True, max_length=32, null=True, verbose_name='地址')),
                ('user', models.CharField(blank=True, max_length=30, null=True, verbose_name='负责人')),
                ('tel', models.CharField(blank=True, max_length=32, null=True, verbose_name='负责人电话')),
            ],
            options={
                'verbose_name': 'idc',
                'verbose_name_plural': 'idc',
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('memo', models.TextField(blank=True, verbose_name='备注')),
                ('hostname', models.CharField(max_length=50, unique=True, verbose_name='主机名')),
                ('an', models.CharField(blank=True, max_length=20, null=True, verbose_name='资产编号')),
                ('sn', models.CharField(blank=True, max_length=20, null=True, verbose_name='机器码')),
                ('ip', models.CharField(max_length=100, unique=True, verbose_name='主IP')),
                ('other_ip', models.CharField(blank=True, max_length=100, null=True, verbose_name='其他IP')),
                ('have_net', models.BooleanField(default=False, verbose_name='有外网')),
                ('gateway', models.CharField(blank=True, max_length=20, null=True, verbose_name='网关')),
                ('asset_type', models.CharField(choices=[(1, '物理机'), (2, '虚拟机'), (3, '容器'), (4, '网络设备'), (5, '其他设备')], default=2, max_length=30, verbose_name='设备类型')),
                ('status', models.CharField(choices=[(1, '使用中'), (2, '未使用'), (3, '故障'), (4, '报废')], default=2, max_length=30, verbose_name='设备状态')),
                ('os', models.CharField(blank=True, max_length=30, null=True, verbose_name='操作系统')),
                ('cpu', models.CharField(blank=True, max_length=100, null=True, verbose_name='CPU信息')),
                ('memory', models.CharField(blank=True, max_length=30, null=True, verbose_name='内存信息')),
                ('disk', models.CharField(blank=True, max_length=100, null=True, verbose_name='硬盘信息')),
                ('groups', models.ManyToManyField(blank=True, related_name='host_group', to='cmdbs.HostGroup', verbose_name='主机组')),
                ('idc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmdbs.Idc', verbose_name='机房')),
            ],
            options={
                'verbose_name': '服务器',
                'verbose_name_plural': '服务器',
            },
        ),
    ]
