# Generated by Django 3.0.3 on 2020-08-17 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('memo', models.TextField(blank=True, verbose_name='备注')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='名称')),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'jenkins任务',
                'verbose_name_plural': 'jenkins任务',
            },
        ),
    ]
