# Generated by Django 3.0.3 on 2020-08-18 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jenkins_tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('memo', models.TextField(blank=True, verbose_name='备注')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='名称')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='code')),
                ('build_id', models.CharField(max_length=64, unique=True, verbose_name='构建id')),
                ('params', models.TextField(blank=True, null=True, verbose_name='一推参数')),
                ('status', models.CharField(choices=[(1, 'running'), (2, 'success'), (3, 'error')], default=2, max_length=1, verbose_name='状态')),
            ],
            options={
                'verbose_name': '任务日志',
                'verbose_name_plural': '任务日志',
            },
        ),
        migrations.AddField(
            model_name='task',
            name='code',
            field=models.CharField(default=1, max_length=64, unique=True, verbose_name='code'),
            preserve_default=False,
        ),
    ]
