# Generated by Django 3.0.3 on 2020-08-22 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jenkins_tasks', '0002_auto_20200818_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklog',
            name='status',
            field=models.CharField(choices=[(1, 'RUNNING'), (2, 'SUCCESS'), (3, 'ABORTED'), (4, 'FAILURE')], default=1, max_length=1, verbose_name='状态'),
        ),
    ]
