# Generated by Django 3.0.3 on 2020-08-22 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jenkins_tasks', '0003_auto_20200822_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklog',
            name='status',
            field=models.CharField(choices=[(1, 'PENDING'), (2, 'RYNNING'), (3, 'SUCCESS'), (4, 'ABORTED'), (5, 'FAILURE')], default=2, max_length=1, verbose_name='状态'),
        ),
    ]
