# Generated by Django 3.0.3 on 2020-08-22 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jenkins_tasks', '0004_auto_20200822_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklog',
            name='code',
            field=models.CharField(max_length=64, verbose_name='code'),
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='name',
            field=models.CharField(max_length=64, verbose_name='名称'),
        ),
    ]
