# Generated by Django 3.0.3 on 2020-08-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jenkins_tasks', '0005_auto_20200822_1452'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasklog',
            options={'ordering': ['-id'], 'verbose_name': '任务日志', 'verbose_name_plural': '任务日志'},
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='status',
            field=models.CharField(choices=[(1, 'PENDING'), (2, 'RUNNING'), (3, 'SUCCESS'), (4, 'ABORTED'), (5, 'FAILURE')], default=2, max_length=1, verbose_name='状态'),
        ),
    ]
