# Generated by Django 3.0.3 on 2020-07-20 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='group',
        ),
        migrations.AddField(
            model_name='chatgroup',
            name='messages',
            field=models.ManyToManyField(blank=True, related_name='messages', to='chats.ChatMessage', verbose_name='消息'),
        ),
    ]
