# Generated by Django 3.0.3 on 2020-07-20 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_auto_20200720_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatgroup',
            name='messages',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chats.ChatGroup', verbose_name='群组'),
            preserve_default=False,
        ),
    ]
