# Generated by Django 3.0.3 on 2020-07-20 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_auto_20200720_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_set', to='chats.ChatGroup', verbose_name='群组'),
        ),
    ]
